# Generated by Django 6.0.6 on 2026-06-28 15:03

import stories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('media_file', models.FileField(upload_to='stories/media/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='stories/audio/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('trim_start', models.FloatField(default=0)),
                ('trim_end', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=stories.models.story_expiry)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
